services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_storage:/var/lib/grafana'
      - './grafana/provisioning:/etc/grafana/provisioning'

  prometheus:
    image: quay.io/prometheus/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - 'prometheus_storage:/prometheus'
      - './prometheus:/etc/prometheus'

  alertmanager:
    image: quay.io/prometheus/alertmanager
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - '9093:9093'
    volumes:
      - 'alertmanager_storage:/alertmanager'
      - './alertmanager:/etc/alertmanager'

  blackbox:
    image: quay.io/prometheus/blackbox-exporter
    container_name: blackbox
    restart: unless-stopped

volumes:
  grafana_storage: {}
  prometheus_storage: {}
  alertmanager_storage: {}
