# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 30s

  external_labels:
    monitor: sysmon-lab

rule_files:
#  - "first.rules"
#  - "my/*.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: nginx
    static_configs:
      - targets: ["192.168.122.18:9113"]

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

