# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: sysmon

rule_files:
#  - "first.rules"
#  - "my/*.rules"

scrape_configs:
  - job_name: ctfd
    scrape_interval: 30s
    static_configs:
      - targets: ["10.22.9.229:2112"]

  - job_name: nginx
    static_configs:
      - targets: ["10.22.9.229:9113"]

  - job_name: redis
    static_configs:
      - targets: ["10.22.9.229:9121"]

  - job_name: mysqld
    static_configs:
      - targets: ["10.22.9.229:9104"]

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://10.22.9.229    # Target to probe with http.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
    scrape_interval: 30s
    static_configs:
      - targets: ['blackbox:9115']

  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
      - targets: ["localhost:9090"]

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

