{
 "title": "CTFd dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Scoreboard",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 20, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ctfd_team_score", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Top 15 teams",
   "type": "table",
   "gridPos": { "h": 16, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ctfd_team_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Solves per category",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(category) (ctfd_challenge_solves)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Least solved challenges",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 5, "y": 16 },
   "targets": [
    { "expr": "ctfd_challenge_solves", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Challenges with most fails",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 11, "y": 16 },
   "targets": [
    {
     "expr": "sum by(name) (ctfd_submission_fails)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 players",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 16 },
   "targets": [
    { "expr": "ctfd_user_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Participants",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ctfd_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Teams",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ctfd_teams_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Challenges",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ctfd_challenges_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "Time left", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 4, "x": 20, "y": 24 } }
 ]
}